[program:pakaiapp-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/pakaiapp-dash/artisan reverb:start --host="127.0.0.1" --port=8080
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
stdout_logfile=/var/log/pakaiapp-reverb.log
